#!/usr/bin/env bash
# Loops from 1 to 10, prints different msg

COUNTER=1
while [ $COUNTER -lt 11 ]; do
      if [ $COUNTER -eq 4 ]
      then
	echo "bad luck"
      elif [ $COUNTER -eq 8 ]
      then
      	echo "good luck"
      else
	echo "Holberton School"
      fi
      let COUNTER=COUNTER+1
done
