#!/usr/bin/env bash
# description

COUNT=1
while [ $COUNT -lt 21 ];
do
      echo $COUNT
      case $COUNT in
      	   4)
		echo "back luck from China"
		;;
	   9)
		echo "back luck from Japan"
		;;
	   17)
		echo "bad luck from Italy"
		;;
      esac
      let COUNT=COUNT+1
done
