#!/usr/bin/env bash
#Bash script

HC=0

while [ $HC -lt 13 ]; do
      MC=1
      echo "Hour: "$HC
      while [ $MC -lt 60 ]; do
      	    echo $MC
	    let MC=MC+1
      done
      let HC=HC+1
done
