#!/usr/bin/env bash
# desscription

hf="holbertonschool"
if [ -e "$hf" ];
then
	echo "holbertonschool file exists"
	if [ -s "$hf" ];
	then
		echo "holbertonschool file is not empty"
		if [ -f "$hf" ];
		then
			echo "holbertonschool file is a regular file"
		fi
	else
		echo "holbertonschool file is empty"
		if [ -f "$hf" ];
		then
			echo "holbertonschool file is a regular file"
		fi
	fi
else
	echo "holbertonschool file does not exist"
fi
