#!/usr/bin/env bash
# blah

holbertonfile="holbertonschool"
if [ -e "$holbertonfile" ];
then
	echo "holbertonschool file exists"
	if [ -s "$holbertonfile" ];
	then
		echo "holbertonschool file is not empty"
		if [ -f "$holbertonfile" ];
		then
			echo "holbertonschool file is a regular file"
		fi
	else
		echo "holbertonschool file is empty"
		if [ -f "$holbertonfile" ];
		then
			echo "holbertonschool file is a regular file"
		fi
	fi
else
	echo "holbertonschool file does not exist"
fi
